/* autogenerated do not edit */
#ifndef OR_TESTSUITE_TAGS_H_
#define OR_TESTSUITE_TAGS_H_
#include "xmlhandler.h"
extern const xml::tag_map_definition_t  testsuitetags[];
enum {
XML_testsuite = 1,
XML_test = 2,
XML_name = 3,
XML_file = 4,
XML_source = 5,
XML_results = 6,
XML_rawType = 7,
XML_rawTypeId = 8,
XML_thumbNum = 9,
XML_thumbSizes = 10,
XML_thumbFormats = 11,
XML_thumbDataSizes = 12,
XML_thumbMd5 = 13,
XML_rawDataType = 14,
XML_rawDataSize = 15,
XML_rawDataDimensions = 16,
XML_rawDataRoi = 17,
XML_rawCfaPattern = 18,
XML_rawMinValue = 19,
XML_rawMaxValue = 20,
XML_rawMd5 = 21,
XML_rawDecompressedMd5 = 22,
XML_metaOrientation = 23,
XML_exifMake = 24,
XML_exifModel = 25,
XML_makerNoteCount = 26,
XML_makerNoteId = 27,
_XML_LASTTOKEN
};
#endif
